# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CV_SWEN_Main <- function(x, y, type, G, include_intercept, alpha_s, alpha_d, n_lambda_sparsity, n_lambda_diversity, tolerance, max_iter, n_folds, active_set, full_diversity, n_threads) {
    .Call('_SplitGLM_CV_SWEN_Main', PACKAGE = 'SplitGLM', x, y, type, G, include_intercept, alpha_s, alpha_d, n_lambda_sparsity, n_lambda_diversity, tolerance, max_iter, n_folds, active_set, full_diversity, n_threads)
}

Split_WEN_Main <- function(x, y, type, G, include_intercept, alpha_s, alpha_d, lambda_sparsity, lambda_diversity, tolerance, max_iter, active_set_convergence) {
    .Call('_SplitGLM_Split_WEN_Main', PACKAGE = 'SplitGLM', x, y, type, G, include_intercept, alpha_s, alpha_d, lambda_sparsity, lambda_diversity, tolerance, max_iter, active_set_convergence)
}

